services:
  - type: web
    name: trading-info-miniapp
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: REACT_APP_API_URL
        value: ""